---
- name: Start and Enable MariaDB service
  service:
    name: mariadb
    state: started
    enabled: yes

- name: Copy my.cnf for MariaDB
  template:
    src: my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0640

- name: Check if root password is set
  shell : mysqladmin -u root status
  failed_when: false
  changed_when: false
  register: check_root_pwd

- name: Set the MariaDB root password for first time
  mysql_user:
    name: root
    password: "{{ mariadb_root_password }}"
    host: localhost
    state: present
  when: check_root_pwd.rc == 0

- name: Secure the root user
  mysql_user:
    name: root
    password: "{{ mariadb_root_password }}"
    host: "{{ item }}"
    login_user: root
    login_password: "{{ mariadb_root_password }}"
  with_items:
    - localhost
    - ::1
    - 127.0.0.1
  when: check_root_pwd.rc == 0

- name: Deletes anonymous user
  mysql_user:
    user: ""
    state: absent

- name: Removes the test database
  mysql_db:
    db: test
    state: absent

- name: Create WordPress DB
  mysql_db:
    name: "{{ wp_db_name }}"
    state: present

- name: Create WordPress username and password
  mysql_user:
    name: "{{ wp_db_username }}"
    password: "{{ wp_db_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    state: present
