---
- name: Download and extract WordPress latest source file
  unarchive:
    src: "{{ wp_tar_location }}"
    dest: /var/www/html
    owner: apache
    group: apache
    extra_opts: ['--strip-components=1']
    remote_src: yes

- name: Copy WordPress configuration file
  template:
    src: wp-config.php.j2
    dest: /var/www/html/wp-config.php
    mode: 0644

- name: Restart HTTPD service
  service:
    name: httpd
    state: restarted
    enabled: yes
